### PR TITLE
Character customization

### PR DESCRIPTION
**Pull request by eff3ry**
This pull request will be adding limited Character Customization to the project

### CODE REVIEW

**Comment by eff3ry** [comment]
Ready For testing

**Comment by eff3ry** [comment]
The menu is in the top left corner of the lobby

**Comment by elsa-menegaux** [comment]
Good for everything except for Battle scene for now. See discord for details.

**Review by elsa-menegaux — APPROVED** [review]
Works perfectly fine now ! Ready to go.

**Pull request merged**
