### PR TITLE
Sprint 1 polish Pull request

### PR DESCRIPTION
**Pull request by SahilDhanda-20122024**
I am creating this pull request so we can merge the working enemy encounter, battle code and bug fixes into the main branch. for description of battle system patch notes view description of previous commit.

### CODE REVIEW

**Comment by elsa-menegaux** [comment]
After review during lab, both Sahil and me noted : 
- good polish of the battle system, especially for the enemy encounter
- very satisfactory context clues like the enemy names and their introduction phrases
- the player can now die, however the restarting the game does not : though it does take you back to room 1, we see no enemy or player for that matter, stats don't change either, as they all stay in their precedent states. We can look into resetting all scenes for that event, it might be an easy fix.
- player speed was suddenly very fast on my part. Maybe a problem because of the different computers that handle player movement ? Something to look into. 
- maybe we can adapt UI for enemy names to be longer

**Comment by SahilDhanda-20122024** [comment]
need to make it so the pause button and pause menu function on all the different levels as currently the pause button only functions on the first map/scene

**Comment by eff3ry** [comment]
> need to make it so the pause button and pause menu function on all the different levels as currently the pause button only functions on the first map/scene

I believe ive fixed this now

**Review by elsa-menegaux — APPROVED** [review]
It should be fine now, merge approved so that this can be the base for sprint 2.

**Pull request merged**
